version: '3.8'
services:
  movies:
    image: purushottambawane805/moviesrepo:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: purushottambawane805/trainrepo:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  recharge:
    image: purushottambawane805/rechargerepo:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  dth:
    image: purushottambawane805/dthrepo:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
